---
swagger: "2.0"
info:
  title: Foursquare
  version: "2"
host: api.foursquare.com
basePath: "/v2"
schemes:
  - https
securityDefinitions:
  oauth2:
    type: oauth2
    flow: accessCode
    in: query
    name: oauth_token
    authorizationUrl: "https://foursquare.com/oauth2/authenticate"
    tokenUrl: "https://foursquare.com/oauth2/access_token"
x-version-parameter:
  name: v
  version: "20140806"
security:
  oauth2: []
paths:
  /users/{user_id}:
    get:
      summary: Returns profile information for a given user
      operationId: getUser
      parameters:
        - name: user_id
          in: path
          required: true
        - name: m
          description: Response style
          in: query
          enum:
            - foursquare
            - swarm
        - name: v
          description: API version
          in: query
  /venues/managed:
    get:
      summary: Get a list of venues the current user manages.
      operationId: getManagedVenues
      parameters:
        - name: limit
          in: query
          type: integer
        - name: offset
          in: query
          type: integer
        - name: v
          description: API version
          in: query

